export const CodeErrors =  new Map()
  CodeErrors.set("1","User not found")
  CodeErrors.set("2","Group doesnt exist")
  CodeErrors.set("3","You are not leader of this group")
  CodeErrors.set("4","Wrong code")
  CodeErrors.set("5","You are already in this group")
  CodeErrors.set("6","User doesnt exist")
  CodeErrors.set("7","User already banned")
  CodeErrors.set("8","Account blocked")
  CodeErrors.set("9","User already reported")

  CodeErrors.set("21","Bad email credentials")
  CodeErrors.set("22","Bad password credentials")
  CodeErrors.set("23","Bad username credentials")
  CodeErrors.set("24","Bad profile name credentials")
  CodeErrors.set("25","Bad group name credentials")
  CodeErrors.set("26","Bad age credentials")
  CodeErrors.set("27","Bad phone credentials")
  CodeErrors.set("28","Bad city credentials")
  CodeErrors.set("29","Bad profile info credentials")
  CodeErrors.set("30","Bad group description credentials")
  CodeErrors.set("31","Email already taken")
  CodeErrors.set("32","Username already taken")
  CodeErrors.set("33","Group name already taken")
